name: Build go binaries
on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'

      - name: Install dependencies
        run: go mod download 

      - name: build server
        run: go build -o ./bin/server ./cmd/server

      - name: build client
        run: go build -o ./bin/client ./cmd/client

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: ./bin
      
      - name: test
      - uses: actions/checkout@v3

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt


