name: Build go binaries and test them
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'


      - name: Install dependencies
        run: go mod download 

      - name: build server
        run: go build -o ./bin/server ./cmd/server

      - name: build client
        run: go build -o ./bin/client ./cmd/client

      - name: copy server to demo
        run: cp ./bin/server ./demo/server

      - name: copy client to demo
        run: cp ./bin/client ./demo/client

      - name: Pull MongoDB Docker image
        run: sudo docker pull mongo

      - name: Start MongoDB container
        run: |
          sudo docker run -d -p 27017:27017 --name mongodb mongo
          sudo docker ps -a

      - name: create database and collection
        run: |
          docker exec -it mongo mongo
          use test
          db.createCollection("test")

      - name: create server params as json
        run: |
            echo '{"port": "8080", "dbconnectionstring": "mongodb://localhost:27017", "collectionname": "test", "databasename": "test", "servername": "test"}' > ./demo/server_params.json

      - name: create the connection string
        run: |
          echo "mongodb://localhost:27017" > ./demo/connection_string.txt

      - name: inspect 
        run: ls -la ./demo
      
      

      
