name: Build go binaries and test them
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'

      - name: run the tests
        run: |
          cd tests
          pip install -r requirements.txt 
          pytest
    
      


