name: test
on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
      run: echo "Hello World1"

      - name: Setup Go
      run: echo "Hello World2"
